const problemsData = [
  {
    days: 1,
    problems: [
      {
        number: "1",
        name: "datatype",
        description: "Understand basic of python varible types",
        image: "/questionicon/day1/N1.png",
        url: "https://smth.com",
      },
      {
        number: "2",
        name: "Basic Operations",
        description: "Explore the use of +, -, *, /, //, and % operations on strings and integers.",
        image: "/questionicon/day1/N2.png",
        url: "https://smth.com",
      },
      {
        number: "3",
        name: "Assigning",
        description: "understand how to update the value of an existing variable",
        image: "/questionicon/day1/N3.png",
        url: "https://smth.com",
      },
      {
        number: "4",
        name: "Comparing",
        description: "Understand how to compare variables in Python.",
        image: "/questionicon/day1/N4.png",
        url: "https://smth.com",
      },
      {
        number: "5",
        name: "type casting, input",
        description: "'Hello', Yessssss, I can hear now :)",
        image: "/questionicon/day1/N5.png",
        url: "https://smth.com",
      },
      {
        number: "6",
        name: "Length of String",
        description: "Sometimes, a computer needs to count—and len() is a handy tool for the job.",
        image: "/questionicon/day1/N6.png",
        url: "https://smth.com",
      },
      {
        number: "7",
        name: "f-string",
        description: "Learn how to format strings to make them look better.",
        image: "/questionicon/day1/N7.png",
        url: "https://smth.com",
      },
      {
        number: "8",
        name: "if-else 1",
        description: "When it comes to calculating grades, if/else logic is where it all begins.",
        image: "/questionicon/day1/N8.png",
        url: "https://smth.com",
      },
      {
        number: "9",
        name: "If-else 2",
        description: "Is it triangle?",
        image: "/questionicon/day1/N9.png",
        url: "https://smth.com",
      },
      {
        number: "10",
        name: "String modify",
        description: "UPPER? lower? will it be useful somehow?",
        image: "/questionicon/day1/N10.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 1",
        name: "How Many Sheep?",
        description: "I wonder why I can't sleep. Maybe modulus is the key.",
        image: "/questionicon/day1/E1.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 2",
        name: "Parking Fee Calculation",
        description: "Adapt the if/elif/else structure to a different level of the program.",
        image: "/questionicon/day1/E2.png",
        url: "https://smth.com",
      },
    ],
  },
  {
    days: 2,
    problems: [
      {
        number: "1",
        name: "List-access",
        description: "Accessing list elements using an index.",
        image: "/questionicon/day2/N1.png",
        url: "https://smth.com",
      },
      {
        number: "2",
        name: "List modify",
        description: "Add an element to a list and manage the updated contents.",
        image: "/questionicon/day2/N2.png",
        url: "https://smth.com",
      },
      {
        number: "3",
        name: "List Slicing",
        description: "Time to Slicing (Banana). Got it? :P",
        image: "/questionicon/day2/N3.png",
        url: "https://smth.com",
      },
      {
        number: "4",
        name: "List to string",
        description: "'Together' is easy, but 'To Get Her' is impossible.",
        image: "/questionicon/day2/N4.png",
        url: "https://smth.com",
      },
      {
        number: "5",
        name: "Tuple",
        description: "A tuple is like a list, but you can't change its contents.",
        image: "/questionicon/day2/N5.png",
        url: "https://smth.com",
      },
      {
        number: "6",
        name: "Set",
        description: "A set is like the evolutionary step backward from a list—no order, no duplicates, just raw values.",
        image: "/questionicon/day2/N6.png",
        url: "https://smth.com",
      },
      {
        number: "7",
        name: "Dict 1",
        description: "Fix the value in a dictionary by referencing its key.",
        image: "/questionicon/day2/N7.png",
        url: "https://smth.com",
      },
      {
        number: "8",
        name: "Dict 2",
        description: "Something's missing—perhaps using .keys() could help.",
        image: "/questionicon/day2/N8.png",
        url: "https://smth.com",
      },
      {
        number: "9",
        name: "Are they even or odd?",
        description: "Basic For loop (range)",
        image: "/questionicon/day2/N9.png",
        url: "https://smth.com",
      },
      {
        number: "10",
        name: "in-class number",
        description: "Basic For loop with list.",
        image: "/questionicon/day2/N10.png",
        url: "https://smth.com",
      },
      {
        number: "11",
        name: "List comprehension",
        description: "Did you know that a list and a for loop can be written in a single line?",
        image: "/questionicon/day2/N11.png",
        url: "https://smth.com",
      },
    ],
  },
  {
    days: 3,
    problems: [
      {
        number: "1",
        name: "Basic Function",
        description: "Basic use of function",
        image: "/questionicon/day3/N1.png",
        url: "https://smth.com",
      },
      {
        number: "2",
        name: "Mathematics module",
        description: "Combine the math module with a subroutine to perform calculations.",
        image: "/questionicon/day3/N2.png",
        url: "https://smth.com",
      },
      {
        number: "3",
        name: "Random Module 1",
        description: "Learning Random module with dice",
        image: "/questionicon/day3/N3.png",
        url: "https://smth.com",
      },
      {
        number: "4",
        name: "Random Module 2",
        description: "Learning Random module with with realife(?) example",
        image: "/questionicon/day3/N4.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 1",
        name: "TupleNana Again!?",
        description: "Everything is Banana. MuHaHaHaHaHaHa.",
        image: "/questionicon/day3/E1.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 2",
        name: "Cipher Scroll Recovery",
        description: "An ancient digital artifact",
        image: "/questionicon/day3/E2.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 3",
        name: "Password",
        description: "I wanna login~ Please let me in!",
        image: "/questionicon/day3/E3.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 4",
        name: "You cannot escape math",
        description: "Learning to do sequence.",
        image: "/questionicon/day3/E4.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 5",
        name: "Greg the chicken",
        description: "Feed a Mystical Chicken (Quack)",
        image: "/questionicon/day3/E5.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 6",
        name: "No if-Else!!",
        description: "Nooo, not the if/else. It's important. TvT",
        image: "/questionicon/day3/E6.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 7",
        name: "Python can be hard >:)",
        description: "Python + Algo + Linear = WHAT DA HELLLLLLLL!",
        image: "/questionicon/day3/E7.png",
        url: "https://smth.com",
      },
      {
        number: "Extra 8",
        name: "Continue the Tradition",
        description: "Impossibly impossible Challenge",
        image: "/questionicon/day3/E8.png",
        url: "https://youtu.be/xvFZjo5PgG0?si=EvwKqoycOQXi0hmu",
      },
    ],
  },
];

export default problemsData;
